import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '10.43.0';

@internal
const productionIntegrity =
    'sha384-RmcJ26nQdXSMBe8cChuJflaz8GlPDeX/WRJ6cByT/nn9t8J0jI3dAmI7UmZOQn5n';

@internal
const debugIntegrity =
    'sha384-/CIDrrR0CaHnhCjIvxyN8GlysSqU4JsCq4+tVw4ka9/7E/EaYt/Yx9IwX4k+fI25';
