import 'package:meta/meta.dart';

/// DO NOT EDIT – generated by scripts/update-js.sh
@internal
const sentryJsSdkVersion = '10.49.0';

@internal
const productionIntegrity =
    'sha384-MOE/hT/RYJedcB7gqX8p9h/E7Z4YL/9YZi6KAoCOS7kdW/Ys3mG96N5v6eB3qeSQ';

@internal
const debugIntegrity =
    'sha384-IyESY0D0j2LRBT2CUqbjdZhhHDbaHZdXjGF4GSWvce5iCjsNpMGv019YdtECAPer';
